purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6523297
  brandStrength: 1
  lightness: 0.7168459
  brandColors:
    - '#FFFFFF'
    - '#0F1217'
    - '#518980'
    - '#FBB297'
    - '#D18156'
  rhythmicContrast: 0.797491
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: mct
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4390681
layout_spectrum: 0.1774193
