name: mct
favicon: null
layout_spectrum: 0.9814979683142155
typography_spectrum: 0.49947755807079375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6409721011295915
  lightness: 0.6587094035930932
  saturation: 0.6575071944389492
  rhythmicContrast: 0.9282267866656184
purpose: []
